<?php
// Establish connection to the rental car database
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "keretasewa_db";

$conn = new mysqli($servername, $username, $password, $dbname);

if ($conn->connect_error) {
    die("Database connection failure: " . $conn->connect_error);
}

// Handle Payment Submission
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['submit_payment'])) {
    $bookID = intval($_POST['bookID']);
    $custID = intval($_POST['custID']);
    $carID = intval($_POST['carID']);
    $dayTotal = intval($_POST['dayTotal']);
    $timeTotal = intval($_POST['timeTotalMins']);
    $payTotal = floatval($_POST['payTotal']);
    
    // Handle File Upload for Payment Proof
    $payProofPath = 'imgweb/default-pay.jpg';
    if (isset($_FILES['payProof']) && $_FILES['payProof']['error'] == UPLOAD_ERR_OK) {
        $target_dir = "imgweb/";
        if (!is_dir($target_dir)) mkdir($target_dir, 0777, true);
        
        $fileName = time() . "_" . basename($_FILES["payProof"]["name"]);
        $target_file = $target_dir . $fileName;
        
        if (move_uploaded_file($_FILES["payProof"]["tmp_name"], $target_file)) {
            $payProofPath = $target_file;
        }
    }

    // Insert into Payment Table
    $insert_payment = "INSERT INTO payment (bookID, custID, carID, payTotal, dayTotal, timeTotal, payProof) 
                       VALUES ($bookID, $custID, $carID, $payTotal, $dayTotal, $timeTotal, '$payProofPath')";
    
    if ($conn->query($insert_payment)) {
        header("Location: cust_receipt.php?bookID=" . $bookID);
        exit();
    } else {
        echo "<script>alert('Error submitting payment: " . $conn->error . "');</script>";
    }
}

// Get the specific booking ID
$bookID = isset($_GET['bookID']) ? intval($_GET['bookID']) : (isset($_POST['bookID']) ? intval($_POST['bookID']) : 1);

// Read the penalty rate generated by the admin panel
$penaltyFile = '../admin/penalty_rate.txt';
$penaltyRate = file_exists($penaltyFile) ? floatval(file_get_contents($penaltyFile)) : 10.00;

// Fetch booking, customer, car, and ACTUAL return details from return_update
$query = "SELECT b.*, c.custName, c.custIC, c.contactno, c.custEmail, 
                 car.carBrand, car.carModel, car.carPlate, car.carPrice,
                 ru.returnDate as actualReturnDate, ru.returnTime as actualReturnTime
          FROM booking b
          JOIN customer c ON b.custID = c.custID
          JOIN car ON b.carID = car.carID
          LEFT JOIN return_update ru ON b.bookID = ru.bookID
          WHERE b.bookID = $bookID";

$result = $conn->query($query);

if ($result && $result->num_rows > 0) {
    $row = $result->fetch_assoc();
    
    // 1. Create DateTime objects for Pickup and ACTUAL Return
    $pickupDT = new DateTime($row['pickupDate'] . ' ' . $row['pickupTime']);
    
    // Fallback to original booking date if return_update is missing for any reason
    $actualRetDate = !empty($row['actualReturnDate']) ? $row['actualReturnDate'] : $row['returnDate'];
    $actualRetTime = !empty($row['actualReturnTime']) ? $row['actualReturnTime'] : $row['returnTime'];
    
    $returnDT = new DateTime($actualRetDate . ' ' . $actualRetTime);
    $expectedReturn = new DateTime($row['returnDate'] . ' ' . $row['returnTime']);

    // 2. Calculate the exact time difference
    $interval = $pickupDT->diff($returnDT);
    
    // Convert the entire duration into total minutes for accurate conversion
    $totalMinutes = ($interval->days * 24 * 60) + ($interval->h * 60) + $interval->i;
    
    // Round up to the nearest whole hour (e.g., 2 hours 15 mins becomes 3 hours)
    $totalHoursToCharge = ceil($totalMinutes / 60);
    if ($totalHoursToCharge < 1) $totalHoursToCharge = 1;
    
    // 3. Calculate Total Price (Strictly Hourly)
    $carPricePerHour = floatval($row['carPrice']);
    $baseTotal = $totalHoursToCharge * $carPricePerHour;
    $baseDescrp = "RM " . number_format($carPricePerHour, 2) . "/hr &times; $totalHoursToCharge hrs";
    
    // 4. Format for display (Days and Hours)
    $displayDays = floor($totalHoursToCharge / 24);
    $displayHours = $totalHoursToCharge % 24;
    
    $totalDaysDisplay = $displayDays . " Day(s)";
    $totalHoursDisplay = $displayHours . " Hour(s)";

    // --- PENALTY CALCULATION (If Returned Late) ---
    $overdueHours = 0;
    $penTotal = 0;
    if ($returnDT > $expectedReturn) {
        $overdueDiff = $returnDT->getTimestamp() - $expectedReturn->getTimestamp();
        $overdueHours = ceil($overdueDiff / 3600);
        $penTotal = $overdueHours * $penaltyRate;
    }
    
    $penDescrp = "RM " . number_format($penaltyRate, 2) . "/hr &times; $overdueHours hrs";
    
    $grandTotal = $baseTotal + $penTotal;

} else {
    die("Invalid booking ID. Please ensure the reference number is correct.");
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Payment Method - Abe Nuar Kereta Sewa</title>
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;800&family=Courier+Prime:wght@400;700&display=swap" rel="stylesheet">
  
  <style>
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
      font-family: 'Poppins', sans-serif;
    }

    body {
      background-color: #121212;
      color: #ffffff;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
    }

    /* ================= FIXED NAVIGATION HEADER ================= */
    .header-nav {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      background-color: rgba(18, 18, 18, 0.95);
      backdrop-filter: blur(10px);
      z-index: 1000;
      border-bottom: 1px solid rgba(255, 255, 255, 0.05);
    }

    .nav-container {
      max-width: 1400px;
      margin: 0 auto;
      padding: 20px 40px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .nav-brand {
      color: #ffffff;
      font-size: 1.1rem;
      font-weight: 800;
      letter-spacing: 1px;
      text-transform: uppercase;
    }

    .nav-brand span {
      color: #7b91f9;
    }

    /* ================= PAYMENT SECTION ================= */
    .payment-section {
      padding: 140px 40px 60px 40px;
      max-width: 1200px;
      margin: 0 auto;
      width: 100%;
      flex-grow: 1;
    }

    .section-title {
      font-size: 2.5rem;
      font-weight: 800;
      text-align: center;
      margin-bottom: 15px;
      letter-spacing: 1px;
    }

    .section-subtitle {
      text-align: center;
      color: #7b91f9;
      font-size: 1rem;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 2px;
      margin-bottom: 60px;
    }

    .title-underline {
      width: 60px;
      height: 4px;
      background-color: #7b91f9;
      margin: 10px auto 0 auto;
      border-radius: 2px;
    }

    .payment-container {
      display: grid;
      grid-template-columns: 1.1fr 1.1fr;
      gap: 60px;
      align-items: flex-start;
    }

    /* Left Side Elements (QR & Upload Area) */
    .payment-left {
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      background-color: #1a1a1a;
      padding: 40px;
      border-radius: 16px;
      border: 1px solid rgba(255, 255, 255, 0.05);
    }

    .qr-box {
      width: 100%;
      max-width: 340px;
      aspect-ratio: 1 / 1;
      background-color: #ffffff;
      padding: 20px;
      border-radius: 16px;
      margin: 0 auto 35px auto;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .qr-box img {
      width: 100%;
      height: 100%;
      object-fit: contain;
    }

    .upload-action-row {
      display: flex;
      gap: 15px;
      width: 100%;
      margin-bottom: 20px;
    }

    #hidden-file-input {
      display: none;
    }

    .btn-action {
      flex: 1;
      padding: 14px 24px;
      border-radius: 50px;
      font-size: 0.95rem;
      font-weight: 700;
      border: none;
      cursor: pointer;
      text-align: center;
      transition: background-color 0.3s ease, transform 0.2s ease, box-shadow 0.3s ease;
    }

    .btn-upload {
      background-color: #7b91f9;
      color: #ffffff;
      box-shadow: 0 4px 15px rgba(123, 145, 249, 0.3);
    }

    .btn-upload:hover {
      background-color: #6c7fd8;
      transform: translateY(-2px);
    }

    .btn-preview {
      background-color: transparent;
      color: #ffffff;
      border: 2px solid rgba(255, 255, 255, 0.2);
    }

    .btn-preview:hover {
      background-color: rgba(255, 255, 255, 0.05);
      border-color: rgba(255, 255, 255, 0.4);
    }

    .status-text {
      color: #dc2626;
      font-size: 0.85rem;
      font-weight: 600;
      letter-spacing: 0.5px;
      width: 100%;
      text-align: center;
    }

    /* Vibration Keyframe Effect */
    .vibrate {
      animation: vibrate-anim 0.3s linear;
    }

    @keyframes vibrate-anim {
      0%, 100% { transform: translateX(0); }
      20%, 60% { transform: translateX(-6px); }
      40%, 80% { transform: translateX(6px); }
    }

    /* ================= DARK THEME RECEIPT STYLING ================= */
    .payment-right {
      display: flex;
      justify-content: center;
      align-items: center;
      width: 100%;
    }

    .receipt-card {
      width: 100%;
      max-width: 480px;
      background-color: #1a1a1a;
      border: 1px solid rgba(255, 255, 255, 0.05);
      border-radius: 16px;
      padding: 35px;
      font-family: 'Courier Prime', monospace;
      color: #e0e0e0;
      box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
    }

    .receipt-header {
      text-align: center;
      margin-bottom: 25px;
    }

    .receipt-title {
      font-family: 'Courier Prime', monospace;
      font-size: 1.4rem;
      font-weight: 700;
      letter-spacing: 1px;
      margin-bottom: 5px;
      color: #ffffff;
    }

    .receipt-meta {
      font-size: 0.85rem;
      color: #888888;
      line-height: 1.5;
    }

    .receipt-divider {
      border: none;
      border-top: 1px dashed rgba(255, 255, 255, 0.15);
      margin: 20px 0;
    }

    .receipt-section-title {
      font-size: 0.9rem;
      font-weight: 700;
      color: #888888;
      margin-bottom: 10px;
      text-transform: uppercase;
    }

    .receipt-row {
      display: flex;
      justify-content: space-between;
      font-size: 0.95rem;
      margin-bottom: 8px;
    }

    .receipt-row .label {
      color: #aaaaaa;
    }

    .receipt-row .value {
      color: #ffffff;
      font-weight: 700;
    }

    .receipt-total-row {
      display: flex;
      justify-content: space-between;
      font-size: 1.2rem;
      font-weight: 700;
      color: #7b91f9;
      margin-top: 15px;
    }

    .receipt-footer {
      text-align: center;
      font-size: 0.85rem;
      color: #666666;
      margin-top: 30px;
      letter-spacing: 0.5px;
    }

    /* ================= NAVIGATION BUTTON ROW ================= */
    .bottom-nav-row {
      display: flex;
      justify-content: flex-end;
      gap: 15px;
      margin-top: 50px;
      width: 100%;
    }

    .btn-nav {
      background-color: transparent;
      color: #ffffff;
      border: 2px solid rgba(255, 255, 255, 0.2);
      padding: 12px 35px;
      border-radius: 50px;
      font-size: 0.9rem;
      font-weight: 600;
      cursor: pointer;
      min-width: 120px;
      text-align: center;
      transition: all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1);
    }

    .btn-submit-pay {
      background-color: #7b91f9;
      color: #ffffff;
      border-color: #7b91f9;
    }

    /* Enlarge and turn white on touch/hover */
    .btn-nav:hover, .btn-nav:active {
      background-color: #ffffff;
      color: #121212;
      border-color: #ffffff;
      transform: scale(1.08);
      box-shadow: 0 6px 20px rgba(255, 255, 255, 0.15);
    }

    .btn-submit-pay:hover {
      background-color: #ffffff;
      color: #121212;
      border-color: #ffffff;
    }

    /* ================= MODAL BASE OVERLAY STYLING ================= */
    .modal-overlay {
      position: fixed;
      top: 0; left: 0; width: 100%; height: 100%;
      background-color: rgba(0, 0, 0, 0.85);
      backdrop-filter: blur(5px);
      z-index: 2000;
      display: flex;
      align-items: center;
      justify-content: center;
      opacity: 0;
      pointer-events: none;
      transition: opacity 0.3s ease;
    }

    .modal-overlay.active {
      opacity: 1;
      pointer-events: auto;
    }

    .modal-content {
      background-color: #1a1a1a;
      color: #ffffff;
      border: 1px solid rgba(255, 255, 255, 0.1);
      border-radius: 16px;
      width: 90%;
      max-width: 550px;
      overflow: hidden;
      box-shadow: 0 20px 40px rgba(0,0,0,0.6);
      transform: scale(0.9);
      transition: transform 0.3s ease;
      position: relative;
    }

    .modal-overlay.active .modal-content {
      transform: scale(1);
    }

    .modal-header {
      background-color: #242424;
      padding: 20px;
      text-align: center;
      font-size: 1.2rem;
      font-weight: 700;
      border-bottom: 1px solid rgba(255, 255, 255, 0.05);
    }

    .modal-body {
      padding: 30px;
      text-align: center;
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .modal-body img {
      max-width: 100%;
      max-height: 60vh;
      border-radius: 8px;
      border: 1px solid rgba(255, 255, 255, 0.1);
      object-fit: contain;
    }

    .modal-close-btn {
      position: absolute;
      top: 15px;
      right: 20px;
      background: transparent;
      border: none;
      font-size: 1.5rem;
      cursor: pointer;
      color: #aaaaaa;
      z-index: 2010;
    }

    .modal-close-btn:hover {
      color: #ffffff;
    }

    .footer-credits {
      text-align: center;
      padding: 40px 20px;
      color: #555555;
      font-size: 0.9rem;
      border-top: 1px solid rgba(255, 255, 255, 0.05);
    }

    /* Responsive scaling adjustments */
    @media (max-width: 992px) {
      .payment-container {
        grid-template-columns: 1fr;
        gap: 40px;
      }
      .payment-section {
        padding-top: 160px;
      }
    }
  </style>
</head>
<body>

  <!-- Navigation Header Lineup -->
  <header class="header-nav">
    <div class="nav-container">
      <div class="nav-brand">ABE NUAR <span>KERETA SEWA</span></div>
    </div>
  </header>

  <!-- Working Segment Block -->
  <section class="payment-section">
    <h2 class="section-title">Payment Method<div class="title-underline"></div></h2>
    <p class="section-subtitle">Please Scan QR &amp; Upload Receipt</p>

    <!-- Wrapped everything inside the interactive data capture form -->
    <form method="POST" action="" enctype="multipart/form-data" onsubmit="return evaluateSubmission()">
      
      <!-- Engine Payload Configuration (Hidden Inputs) -->
      <input type="hidden" name="submit_payment" value="1">
      <input type="hidden" name="bookID" value="<?php echo $row['bookID']; ?>">
      <input type="hidden" name="custID" value="<?php echo $row['custID']; ?>">
      <input type="hidden" name="carID" value="<?php echo $row['carID']; ?>">
      <input type="hidden" name="dayTotal" value="<?php echo $displayDays; ?>">
      <input type="hidden" name="timeTotalMins" value="<?php echo $totalMinutes; ?>">
      <input type="hidden" name="payTotal" value="<?php echo $grandTotal; ?>">

      <div class="payment-container">
        
        <!-- Interactive Engine Elements (Left side: QR & Actions) -->
        <div class="payment-left">
          <div class="qr-box">
            <!-- Use a relative web path instead of a C:\ drive path -->
            <img src="qr.jpeg" alt="Scan QR to Pay">
          </div>

          <div class="upload-action-row">
            <input type="file" id="hidden-file-input" name="payProof" accept="image/*,.pdf">
            <button type="button" class="btn-action btn-upload" onclick="openSystemExplorer()">Upload File</button>
            <button type="button" class="btn-action btn-preview" onclick="displayPreviewWindow()">Preview File</button>
          </div>

          <div class="status-text" id="statusLabel">*Please upload a photo or file to prove your payment</div>
        </div>

        <!-- Modern Car Rent Receipt Layout (Right side) -->
        <div class="payment-right">
          <div class="receipt-card">
            <div class="receipt-header">
              <h3 class="receipt-title">PAYMENT DETAILS</h3>
              <p class="receipt-meta">DATE: <?php echo date("d/m/Y - H:i:s A"); ?><br>ORDER #<?php echo $row['bookID']; ?></p>
            </div>
            
            <div class="receipt-divider"></div>
            
            <div class="receipt-section-title">Customer Details</div>
            <div class="receipt-row">
              <span class="label">CUSTOMER:</span>
              <span class="value"><?php echo htmlspecialchars($row['custName']); ?></span>
            </div>
            <div class="receipt-row">
              <span class="label">CAR MODEL:</span>
              <span class="value"><?php echo htmlspecialchars($row['carBrand'] . ' ' . $row['carModel']); ?></span>
            </div>
            <div class="receipt-row">
              <span class="label">PLATE NO:</span>
              <span class="value"><?php echo htmlspecialchars($row['carPlate']); ?></span>
            </div>
            
            <div class="receipt-divider"></div>
            
            <div class="receipt-section-title">Rental Metric breakdown</div>
            <div class="receipt-row">
              <span class="label">Duration Display:</span>
              <span class="value"><?php echo $totalDaysDisplay; ?> &amp; <?php echo $totalHoursDisplay; ?></span>
            </div>
            <div class="receipt-row">
              <span class="label">Time Total (mins):</span>
              <span class="value"><?php echo $totalMinutes; ?></span>
            </div>
            <div class="receipt-row">
              <span class="label">Rate Base Calc:</span>
              <span class="value"><?php echo $baseDescrp; ?></span>
            </div>
            <div class="receipt-row">
              <span class="label">Base Cost sub:</span>
              <span class="value">RM <?php echo number_format($baseTotal, 2); ?></span>
            </div>

            <?php if ($overdueHours > 0): ?>
              <div class="receipt-row" style="color: #dc2626;">
                <span class="label" style="color: #dc2626;">Fine Rate Calc:</span>
                <span class="value"><?php echo $penDescrp; ?></span>
              </div>
              <div class="receipt-row" style="color: #dc2626;">
                <span class="label" style="color: #dc2626;">Overdue Penalty:</span>
                <span class="value">RM <?php echo number_format($penTotal, 2); ?></span>
              </div>
            <?php endif; ?>
            
            <div class="receipt-divider"></div>
            
            <div class="receipt-total-row">
              <span>TOTAL PRICE:</span>
              <span>RM <?php echo number_format($grandTotal, 2); ?></span>
            </div>
            
            <div class="receipt-footer">
              THANK YOU FOR USING OUR SERVICE!
            </div>
          </div>
        </div>

      </div>

      <!-- Navigation Line Array -->
      <div class="bottom-nav-row">
        <button type="submit" class="btn-nav btn-submit-pay">Confirm Payment</button>
        <button type="button" class="btn-nav" onclick="window.location.href='index.php'">Home</button>
        <button type="button" class="btn-nav" onclick="window.history.back()">Back</button>
      </div>
    </form>
  </section>

  <!-- Interactive Document Viewer Layer Modal -->
  <div class="modal-overlay" id="previewContainerOverlay">
    <div class="modal-content">
      <button class="modal-close-btn" onclick="hidePreviewWindow()">&times;</button>
      <div class="modal-header">Uploaded Proof Preview</div>
      <div class="modal-body" id="previewSurfaceNode"></div>
    </div>
  </div>

  <footer class="footer-credits">
    &copy; 2026 Abe Nuar Kereta Sewa. All rights reserved.
  </footer>

  <!-- Execution Logic Runtime Block -->
  <script>
    let dynamicResourcePayload = null;

    function openSystemExplorer() {
      document.getElementById('hidden-file-input').click();
    }

    document.getElementById('hidden-file-input').addEventListener('change', function(element) {
      const selectedFileReference = element.target.files[0];
      if (selectedFileReference) {
        if (dynamicResourcePayload) {
          URL.revokeObjectURL(dynamicResourcePayload);
        }
        
        dynamicResourcePayload = URL.createObjectURL(selectedFileReference);
        
        const stateNode = document.getElementById('statusLabel');
        stateNode.style.color = "#7b91f9"; 
        stateNode.innerText = `✓ Document selected: ${selectedFileReference.name}`;
      }
    });

    function evaluateSubmission() {
      const stateNode = document.getElementById('statusLabel');
      const fileInput = document.getElementById('hidden-file-input');
      
      if (!fileInput.value) {
        stateNode.classList.remove('vibrate');
        void stateNode.offsetWidth; 
        stateNode.style.color = "#dc2626";
        stateNode.innerText = "*Please upload your payment file/receipt before attempting to submit.";
        stateNode.classList.add('vibrate');
        return false;
      }
      return true;
    }

    function displayPreviewWindow() {
      if (!dynamicResourcePayload) {
        alert("Please upload your payment file/receipt first before attempting preview.");
        return;
      }

      const interactiveCanvasTarget = document.getElementById('previewSurfaceNode');
      interactiveCanvasTarget.innerHTML = `<img src="${dynamicResourcePayload}" alt="Receipt Document Payload Frame">`;
      
      document.getElementById('previewContainerOverlay').classList.add('active');
    }

    function hidePreviewWindow() {
      document.getElementById('previewContainerOverlay').classList.remove('active');
    }

    window.addEventListener('click', (event) => {
      const containerOverlay = document.getElementById('previewContainerOverlay');
      if (event.target === containerOverlay) {
        hidePreviewWindow();
      }
    });
  </script>

</body>
</html>