<?php
// Establish connection to the rental car database
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "keretasewa_db";

$conn = new mysqli($servername, $username, $password, $dbname);

// Check if database connection succeeds
if ($conn->connect_error) {
    die("Database connection failure: " . $conn->connect_error);
}

// Get the specific booking ID from URL parameters
$bookID = isset($_GET['bookID']) ? intval($_GET['bookID']) : 1;

// Read the penalty rate generated by the admin panel
$penaltyFile = '../admin/penalty_rate.txt';
$penaltyRate = file_exists($penaltyFile) ? floatval(file_get_contents($penaltyFile)) : 10.00;

// Fetch comprehensive customer, car, and booking record WITH the ACTUAL return details from return_update
$query = "SELECT b.*, c.custName, c.custIC, c.contactno, c.custEmail, 
                 car.carBrand, car.carModel, car.carPlate, car.carPrice,
                 ru.returnDate as actualReturnDate, ru.returnTime as actualReturnTime
          FROM booking b
          JOIN customer c ON b.custID = c.custID
          JOIN car ON b.carID = car.carID
          LEFT JOIN return_update ru ON b.bookID = ru.bookID
          WHERE b.bookID = $bookID
          ORDER BY ru.returnDate DESC LIMIT 1";

$result = $conn->query($query);

if ($result && $result->num_rows > 0) {
    $row = $result->fetch_assoc();
    
    // Dynamic formatting variables
    $receiptNo = "#REC-" . str_pad($row['bookID'], 6, "0", STR_PAD_LEFT);
    $receiptDate = date("d F Y");
    
    // 1. Create DateTime objects for Pickup and ACTUAL Return
    $pickupDT = new DateTime($row['pickupDate'] . ' ' . $row['pickupTime']);
    
    // Fallback to original booking date if return_update is missing for any reason
    $actualRetDate = !empty($row['actualReturnDate']) ? $row['actualReturnDate'] : $row['returnDate'];
    $actualRetTime = !empty($row['actualReturnTime']) ? $row['actualReturnTime'] : $row['returnTime'];
    
    $returnDT = new DateTime($actualRetDate . ' ' . $actualRetTime);
    $expectedReturn = new DateTime($row['returnDate'] . ' ' . $row['returnTime']);

    // 2. Calculate the exact time difference
    $interval = $pickupDT->diff($returnDT);
    
    // Convert the entire duration into total minutes
    $totalMinutes = ($interval->days * 24 * 60) + ($interval->h * 60) + $interval->i;
    
    // Round up to the nearest whole hour
    $totalHoursToCharge = ceil($totalMinutes / 60);
    if ($totalHoursToCharge < 1) $totalHoursToCharge = 1; // Minimum 1 hour charge
    
    // 3. Calculate Total Base Price (Strictly Hourly)
    $carPricePerHour = floatval($row['carPrice']);
    $baseTotal = $totalHoursToCharge * $carPricePerHour;
    $baseDescrp = "RM " . number_format($carPricePerHour, 2) . "/hr × $totalHoursToCharge hours";
    
    // 4. Format for display (Days and Hours)
    $displayDays = floor($totalHoursToCharge / 24);
    $displayHours = $totalHoursToCharge % 24;
    
    $totalDaysDisplay = $displayDays . " Day(s)";
    $totalHoursDisplay = $displayHours . " Hour(s)";

    // --- PENALTY CALCULATION (If Returned Late) ---
    $overdueHours = 0;
    $penTotal = 0;
    if ($returnDT > $expectedReturn) {
        $overdueDiff = $returnDT->getTimestamp() - $expectedReturn->getTimestamp();
        $overdueHours = ceil($overdueDiff / 3600);
        $penTotal = $overdueHours * $penaltyRate;
    }
    
    $penDescrp = "RM " . number_format($penaltyRate, 2) . "/hr × $overdueHours hours (Overdue)";
    
    $grandTotal = $baseTotal + $penTotal;
    
} else {
    die("Invalid booking ID. Please ensure the reference number is correct.");
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Customer Receipt</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }
        body { background-color: #0B0F19; color: #F3F4F6; min-height: 100vh; display: flex; flex-direction: column; }
        
        .navbar { background-color: #111827; padding: 20px 40px; display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #1E293B; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }
        .nav-brand { font-size: 20px; font-weight: 800; color: #F3F4F6; text-transform: uppercase; letter-spacing: 1px; }
        .nav-brand span { color: #7E99FF; }
        .nav-btn { background-color: #7E99FF; color: #FFFFFF; padding: 10px 20px; border-radius: 8px; text-decoration: none; font-size: 15px; font-weight: 600; }
        .nav-btn:hover { background-color: #6B88FF; }

        .main-container { padding: 50px 20px; display: flex; justify-content: center; flex-grow: 1; }
        .receipt-box { background-color: #111827; border: 1px solid #1E293B; border-radius: 12px; width: 100%; max-width: 750px; box-shadow: 0 10px 25px rgba(0, 0, 0, 0.5); overflow: hidden; position: relative; }
        .receipt-box::before { content: ''; position: absolute; top: 0; left: 0; width: 100%; height: 4px; background: linear-gradient(90deg, #7E99FF, #A3B8FF); }

        .receipt-header { padding: 40px 40px 20px 40px; display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 1px solid #1E293B; }
        .header-left h1 { font-size: 32px; color: #F3F4F6; margin-bottom: 8px; letter-spacing: 0.5px; }
        .header-left p { color: #94A3B8; font-size: 14px; }
        .header-right { text-align: right; }
        .header-right .rec-num { font-size: 18px; color: #7E99FF; font-weight: 700; margin-bottom: 5px; }
        .header-right .rec-date { color: #94A3B8; font-size: 14px; }

        .receipt-body { padding: 30px 40px; }
        
        .customer-info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 30px; margin-bottom: 40px; }
        .info-block h3 { font-size: 12px; text-transform: uppercase; color: #94A3B8; letter-spacing: 1px; margin-bottom: 10px; border-bottom: 1px solid #1E293B; padding-bottom: 8px; }
        .info-block p { font-size: 15px; color: #F3F4F6; margin-bottom: 5px; font-weight: 500; }
        .info-block p span { color: #94A3B8; width: 80px; display: inline-block; font-size: 14px; }

        .receipt-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .receipt-table th { background-color: #0F172A; color: #94A3B8; font-size: 12px; text-transform: uppercase; padding: 15px; text-align: left; border-bottom: 1px solid #1E293B; }
        .receipt-table td { padding: 18px 15px; color: #F3F4F6; font-size: 15px; border-bottom: 1px solid #1E293B; }
        .right-align { text-align: right !important; }

        .receipt-totals { width: 100%; max-width: 350px; margin-left: auto; }
        .total-row { display: flex; justify-content: space-between; padding: 10px 15px; color: #94A3B8; font-size: 15px; }
        .grand-total { font-size: 20px; font-weight: 800; color: #F3F4F6; background-color: #0F172A; border-radius: 8px; padding: 15px; margin-top: 10px; border: 1px solid #1E293B; }
        .grand-total span:last-child { color: #7E99FF; }

        .receipt-footer { padding: 30px 40px; text-align: center; border-top: 1px solid #1E293B; color: #64748B; font-size: 13px; line-height: 1.6; }
        
        @media (max-width: 600px) {
            .customer-info-grid { grid-template-columns: 1fr; gap: 20px; }
            .receipt-header { flex-direction: column; gap: 20px; }
            .header-right { text-align: left; }
            .receipt-totals { max-width: 100%; }
        }
    </style>
</head>
<body>

    <header class="navbar">
        <div class="nav-brand">Abe Nuar <span>Kereta Sewa</span></div>
        <a href="../auth/index.php" class="nav-btn">Return Home</a>
    </header>

    <div class="main-container">
        <main class="receipt-box">
            <div class="receipt-header">
                <div class="header-left">
                    <h1>Payment Receipt</h1>
                    <p>Transaction successfully processed</p>
                </div>
                <div class="header-right">
                    <div class="rec-num"><?php echo htmlspecialchars($receiptNo); ?></div>
                    <div class="rec-date">Date: <?php echo htmlspecialchars($receiptDate); ?></div>
                </div>
            </div>

            <div class="receipt-body">
                <div class="customer-info-grid">
                    <div class="info-block">
                        <h3>Customer Details</h3>
                        <p><span>Name:</span> <?php echo htmlspecialchars($row['custName']); ?></p>
                        <p><span>IC No:</span> <?php echo htmlspecialchars($row['custIC']); ?></p>
                        <p><span>Phone:</span> <?php echo htmlspecialchars($row['contactno']); ?></p>
                    </div>
                    <div class="info-block">
                        <h3>Rental Details</h3>
                        <p><span>Vehicle:</span> <?php echo htmlspecialchars($row['carBrand'] . ' ' . $row['carModel']); ?></p>
                        <p><span>Plate:</span> <?php echo htmlspecialchars($row['carPlate']); ?></p>
                        <p><span>Pick-up:</span> <?php echo date('d/m/y g:i A', $pickupDT->getTimestamp()); ?></p>
                        <p><span>Returned:</span> <?php echo date('d/m/y g:i A', $returnDT->getTimestamp()); ?></p>
                    </div>
                </div>

                <div class="invoice-items">
                    <table class="receipt-table">
                        <thead>
                            <tr>
                                <th>Description</th>
                                <th class="right-align">Amount (RM)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    <span style="display: block; font-weight: 600; color: #F3F4F6;">Base Rental Fee</span>
                                    <span style="font-size: 12px; color: #94A3B8;"><?php echo htmlspecialchars($baseDescrp); ?></span>
                                </td>
                                <td class="right-align"><?php echo number_format($baseTotal, 2); ?></td>
                            </tr>
                            <?php if ($overdueHours > 0): ?>
                            <tr>
                                <td>
                                    <span style="display: block; font-weight: 600; color: #EF4444;">Overdue Penalty</span>
                                    <span style="font-size: 12px; color: #94A3B8;"><?php echo htmlspecialchars($penDescrp); ?></span>
                                </td>
                                <td class="right-align" style="color: #EF4444;"><?php echo number_format($penTotal, 2); ?></td>
                            </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>

                    <div class="receipt-totals">
                        <div class="total-row">
                            <span>Total Duration:</span>
                            <span><?php echo htmlspecialchars($totalDaysDisplay . " & " . $totalHoursDisplay); ?></span>
                        </div>
                        <div class="total-row grand-total">
                            <span>Total Price:</span>
                            <span>RM <?php echo number_format($grandTotal, 2); ?></span>
                        </div>
                    </div>

                    <div class="receipt-footer">
                        <p>Thank you for choosing Abe Nuar Kereta Sewa.</p>
                        <p>This is a computer-generated receipt and requires no signature.</p>
                    </div>
                </div>
            </div>
        </main>
    </div>

</body>
</html>
<?php $conn->close(); ?>